spring.application.name=springmodules

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Root@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# custom User Creation for Security using application.properties

spring.security.user.name=my_username
spring.security.user.password=my_password
spring.security.user.roles=ADMIN

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.jdbc.table-name=SPRING_SESSION
server.servlet.session.timeout = 1m
